//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mavtozavr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public System.Guid Id { get; set; }
        public DeviceTypes DeviceType { get; set; }
        public string SerialNumber { get; set; }
        public string InventoryNumber { get; set; }
    
        public virtual Kits Kits { get; set; }
    }
}
