//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mavtozavr
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePositions
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public double Price { get; set; }
        public int Qantity { get; set; }
        public string Barcode { get; set; }
    
        public virtual Invoices Invoice { private get; set; }
    }
}
