//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mavtozavr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kits
    {
        public int Id { get; set; }
        public string WorkKitId { get; set; }
        public int DeviceId { get; set; }
    
        public virtual Devices Devices { private get; set; }
        public virtual WorkKits WorkKits { private get; set; }
    }
}
