//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mavtozavr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ListModelContainer : DbContext
    {
        public ListModelContainer()
            : base("name=ListModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orgs> Orgs { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<InvoicePositions> InvoicePositions { get; set; }
        public virtual DbSet<TraidPoints> TraidPoints { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Kits> Kits { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
    }
}
