//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mavtozavr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraidPoints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraidPoints()
        {
            this.Sales = new HashSet<Sales>();
            this.Invoices = new HashSet<Invoices>();
            this.Kits = new HashSet<Kits>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Kpp { get; set; }
        public TraidPointTypes TraidPointType { get; set; }
        public string Egais { get; set; }
        public string UTMVersion { get; set; }
        public string GOSTDate { get; set; }
        public string PKIDate { get; set; }
        public string POSVersion { get; set; }
        public string SyncTime { get; set; }
        public string POSid { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { private get; set; }
        public virtual Orgs Org { get; set; }
        public virtual Cities City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kits> Kits { get; set; }
    }
}
