//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mavtozavr
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkKits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkKits()
        {
            this.Kits = new HashSet<Kits>();
        }
    
        public int Id { get; set; }
        public int TradePointId { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kits> Kits { private get; set; }
        public virtual TraidPoints TraidPoints { private get; set; }
    }
}
